config/routes.rb
Rails.application.routes.draw do

  get 'comments/new'
  root 'pages#index'
  get 'sessions/new'
  get 'pages/help'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources 'users'
  resources 'topics'

  get 'favorites/index'
  post '/favorites', to: 'favorites#create'
  get '/favorites', to: 'favorites#index'

  resources 'comments'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  validates :body, {presence: true, length: {maximum: 6}, length: {minimum: 4}}
  validates :body2, {presence: true, length: {maximum: 8}, length: {minimum: 6}}
  validates :body3, {presence: true, length: {maximum: 6}, length: {minimum: 4}}
  validates :user_id, presence: true

  belongs_to :user
  belongs_to :topic

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :topic

end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :user_id, presence: true
  validates :description, presence: true
  validates :image, presence: true

  belongs_to :user
  has_many :favorites
  has_many :favorite_users, through: :favorites, source: 'user'

  mount_uploader :image, ImageUploader

  has_many :comments
  has_many :comments_users, through: :comments, source: 'user'

end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true

  has_many :topics
  has_many :favorites
  has_many :favorite_topics, through: :favorites, source: 'topic'

  has_secure_password

  has_many :comments
  has_many :comment_topics, through: :comments, source: 'topic'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new(topic_id: params[:topic_id])
  end

  def create
    @comment = current_user.comments.new(comment_params)
    @comment.topic_id = params[:comment][:topic_id]

    if @comment.save
      redirect_to topics_path, notice: 'コメントに成功しました'
    else
      flash.now[:alert] = "コメントに失敗しました"
      render :new
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:body, :body2, :body3)
    end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def index
    @favorite_topics = current_user.favorite_topics
  end

  def create
    favorite = Favorite.new
    favorite.user_id = current_user.id
    favorite.topic_id = params[:topic_id]
    if favorite.save
      redirect_to topics_path, notice: 'お気に入りに登録しました'
    else
      redirect_to topics_path, notice: 'お気に入り登録に失敗しました'
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end

  def help
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    # ↓入力されたemailの情報を取得し、一致するユーザーがいるか検索
    user = User.find_by(email: params[:session][:email])
    # ↓userのパスワードが正しいかどうか確認
    if user && user.authenticate(params[:session][:password])
      # ↓「userが存在している。かつ、userのパスワードが正しければ。」
      log_in user
      redirect_to root_path, notice: 'ログインに成功しました'
    else
      # ↓どちらかでも正しくなければ
      flash.now[:alert] = "ログインに失敗しました"
      render 'new'
    end
  end


  # def destroy
  #   log_out
  #   redirect_to root_url
  # end


  private
  # ↓log_inメソッド内でログイン情報を保存
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
  #↓session.deleteはRailsに事前定義されているメソッド、sessionを削除する
    session.delete(:user_id)
    @current_user = nil
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def new
    @topic = Topic.new
  end

  def create
    @topic = current_user.topics.new(topic_params)
    if @topic.save
      redirect_to topics_path, notice: '投稿に成功しました'
    else
      flash.now[:alert] = '投稿に失敗しました'
      render :new
    end
  end

  def index
    @topics = Topic.all.includes(:favorite_users)
  end

  private
  def topic_params
    params.require(:topic).permit(:image, :description)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    # paramsのセキュリティ:ストロングパラメーター使い、正常な情報のみ受け取る設定する → privateメソッドを追加する
    # @user = User.new(name: params[:user][:name], email: params[:user][:email])↓に書き換える
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, notice: '登録が完了しました'
    else
      flash.now[:alert] = "登録に失敗しました"
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<div class="topic-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">コメントを書いて下さい</h1>
        <%= form_for @comment do |f| %>


        <div class="form-group">
          <%= f.label :"1行目(4~6文字)" %>
          <%= f.text_area :body, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :"2行目(6~8文字)" %>
          <%= f.text_area :body2, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :"3行目(4~6文字)" %>
          <%= f.text_area :body3, class: 'form-control' %>
        </div>

          <%= f.submit '投稿', class: 'btn btn-black btn-block' %>
          <%= f.hidden_field :topic_id, value: @comment.topic_id %>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/favorites/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @favorite_topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>
            <%= image_tag topic.image.url %>
            <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
            <p class="topic-text">
              <%= topic.description %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pictgram</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top navbar-transparent">
      <div class="container">
        <%= link_to root_path do %>
          <span><%= image_tag 'icons/logo.png', class: 'navbar-brand' %></span>
        <% end %>
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li>
              <%= link_to '#' do %>
                <%= image_tag 'icons/heart.png' %>
              <% end %>
            </li>
            <li>
              <%= link_to new_topic_path do %>
                <%= image_tag 'icons/camera.png' %>
              <% end %>
            </li>
            <li>
              <%= link_to logout_path, method: :delete do %>
                <%= image_tag 'icons/logout.png' %>
              <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to new_user_path do %>
                <%= image_tag 'icons/register.png' %>
              <% end %>
            </li>
            <li>
              <%= link_to login_path do %>
                <%= image_tag 'icons/login.png' %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
  </body>

</html>

app/views/pages/index.html.erb
<div class="top-hero-wrapper text-center">
  <div class="container top-hero-container">
    <h1 class="text-white">Make you Happy</h1>
    <h2 class="text-white">Pictgram is a service that you can post photos.</h2>
    <div class="row">
      <div class="col-md-offset-3 col-md-3">
        <%= link_to 'Sign in', '#', class: 'btn btn-block btn-white' %>
      </div>
      <div class="col-md-3">
        <%= link_to 'Log in', '#', class: 'btn btn-block btn-white' %>
      </div>
    </div>
  </div>
</div>

app/views/topics/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>
            <%= image_tag topic.image.url %>

              <% if !topic.favorite_users.include?(current_user) %>
                <%= link_to favorites_path(topic_id: topic.id), method: :post do %>
                  <%= image_tag 'icons/heart-black.png', class: 'topic-index-icon' %>
                <% end %>
              <% end %>

                <%= link_to new_comment_path(topic_id: topic.id) do %>
                  <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
                <% end %>

            <p class="topic-text">
              <%= topic.description %>
            </p>

              <h3 class="topic-author">コメント</h3>
              <% topic.comments.each do |comment| %>
                <p class="topic-text"><%= comment.body %></p>
                <p class="topic-text"><%= comment.body2 %></p>
                <p class="topic-text"><%= comment.body3 %></p>
              <% end %>

          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<div class="topic-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Add Picture</h1>
        <%= form_for @topic do |f| %>
        <div class="form-group">
          <%= f.label :image %>
          <%= f.file_field :image %>
        </div>

        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_area :description, class: 'form-control' %>
        </div>

          <%= f.submit '投稿', class: 'btn btn-black btn-block' %>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-white">Sign in</h1>
        <%= form_for @user do |f| %>
        <div class="form-group">
          <%= f.label :name, class: 'text-white' %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :email, class: 'text-white' %>
          <%= f.text_field :email, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :password, class: 'text-white' %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation, class: 'text-white' %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>

        <%= f.submit "登録", class: 'btn-block btn-white' %>
        <% end %>
        <%= link_to 'ログインはこちら', '#', class: 'text-white' %>
      </div>
    </div>
  </div>
</div>